config/routes.rb
Rails.application.routes.draw do

  resources :audit_logs do
    member do
      get :confirm
    end
  end

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  devise_for :users, skip: [:registrations]
  root to: "static#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @pending_approvals = Post.where(status: 'submitted').includes(:user)
    @recent_audit_items = AuditLog.includes(:user).last(10)
  end
end

app/views/welcome/_confirmation_log.html.erb
<% recent_audit_items.each do |recent_audit_item| %>
	<div class='homepage-block col-md-3'>
		<h4>
			<%= recent_audit_item.user.full_name %>
		</h4>

		<p>
			<span class='pending-details'>Week starting:</span> <%= recent_audit_item.start_date %>
		</p>

		<p>
			<span class='pending-details'>Confirmed at:</span> <%= recent_audit_item.end_date || status_label('pending') %>
		</p>

		<p>
			<span class='pending-details'>Status:</span> <%= status_label recent_audit_item.status %>
		</p>
	</div>
<% end %>

app/views/welcome/_pending_approval.html.erb
<% pending_approvals.each do |pending_approval| %>
	<div class='homepage-block col-md-3'>
		<h4>
			<%= pending_approval.user.full_name %>
		</h4>

		<p>
			<span class='pending-details'>Date Submitted:</span> <%= pending_approval.date %>
		</p>

		<p>
			<span class='pending-details'>Rationale:</span> <%= truncate pending_approval.rationale, length: 45 %>
		</p>

		<div class='row'>
			<div class='col-md-6 column'>
				<%= link_to 'Approve', approve_post_path(pending_approval), class: 'btn btn-success btn-block', id: "approve_#{pending_approval.id}" %>
			</div>
			<div class='col-md-6 column'>
				<%= link_to 'Review', edit_post_path(pending_approval), class: 'btn btn-warning btn-block' %>
			</div>
		</div>
	</div>
<% end %>

app/views/welcome/index.html.erb
<% if admin_types.include?(current_user.try(:type)) %>
	<%= render 'static/admin' %>
<% else %>
	<%= render 'static/employee' %>
<% end %>